theme: minima
author: Joel Pick
title: Joel Pick
email: joel.l.pick@gmail.com
description: Feel free to contact me or use the links to keep up with what I'm doing 
twitter_username: joel_l_pick
github_username: joelpick
header_pages:
  - Research/index.md
  - Publications.md
  - R_packages.md
  - blog/index.md